//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LameSoft.SniffThat.Plugins.ListVisualModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ListResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ListResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LameSoft.SniffThat.Plugins.ListVisualModule.ListResources", typeof(ListResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string bDown {
            get {
                return ResourceManager.GetString("bDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string bUp {
            get {
                return ResourceManager.GetString("bUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string cbInvert {
            get {
                return ResourceManager.GetString("cbInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Seen.
        /// </summary>
        internal static string ColFirstSeen {
            get {
                return ResourceManager.GetString("ColFirstSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        internal static string ColLastSeen {
            get {
                return ResourceManager.GetString("ColLastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string ColLatitude {
            get {
                return ResourceManager.GetString("ColLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string ColLong {
            get {
                return ResourceManager.GetString("ColLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP Mac.
        /// </summary>
        internal static string ColMAC {
            get {
                return ResourceManager.GetString("ColMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prot..
        /// </summary>
        internal static string ColProtected {
            get {
                return ResourceManager.GetString("ColProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID.
        /// </summary>
        internal static string ColSSID {
            get {
                return ResourceManager.GetString("ColSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string ColStrength {
            get {
                return ResourceManager.GetString("ColStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gps Info.
        /// </summary>
        internal static string GpsInfo {
            get {
                return ResourceManager.GetString("GpsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string GpsInfoDistance {
            get {
                return ResourceManager.GetString("GpsInfoDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        internal static string itemOrderByNr {
            get {
                return ResourceManager.GetString("itemOrderByNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID.
        /// </summary>
        internal static string itemOrderBySSID {
            get {
                return ResourceManager.GetString("itemOrderBySSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string itemOrderByStrength {
            get {
                return ResourceManager.GetString("itemOrderByStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string itemOrderByVisibility {
            get {
                return ResourceManager.GetString("itemOrderByVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a List of all known Access Points.
        /// </summary>
        internal static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        internal static string lOrderBy {
            get {
                return ResourceManager.GetString("lOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Access Points, {1} visible.
        /// </summary>
        internal static string lStatusFormat {
            get {
                return ResourceManager.GetString("lStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr.
        /// </summary>
        internal static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB.
        /// </summary>
        internal static string SignalStrengthDB {
            get {
                return ResourceManager.GetString("SignalStrengthDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Rates.
        /// </summary>
        internal static string SupportedRates {
            get {
                return ResourceManager.GetString("SupportedRates", resourceCulture);
            }
        }
    }
}
